const express=require('express');
const auth=require('../middlewares/authMiddleware');
const perfil=require('../middlewares/perfilMiddleware');
const permitir=require('../middlewares/permissaoMiddleware');
const controller=require('../controllers/GestaoController');
const router=express.Router();
router.use(auth);
router.get('/notificacoes',controller.notificacoes);
router.patch('/notificacoes/:id/ler',controller.lerNotificacao);
router.post('/dispositivos/push',controller.registrarPush);
router.get('/contratos',perfil('GESTOR','ADMIN'),permitir('GESTAO_VISUALIZAR'),controller.listarContratos);
router.post('/contratos',perfil('GESTOR','ADMIN'),permitir('GESTAO_GERENCIAR'),controller.criarContrato);
router.post('/contratos/:id/gerar-visita',perfil('GESTOR','ADMIN'),permitir('GESTAO_GERENCIAR'),controller.gerarVisita);
router.get('/relatorios/gerencial',perfil('GESTOR','ADMIN'),permitir('GESTAO_VISUALIZAR'),controller.relatorio);
router.get('/agenda/gestao',perfil('GESTOR','ADMIN'),permitir('GESTAO_VISUALIZAR'),controller.agenda);
router.get('/configuracoes/permissoes',perfil('GESTOR','ADMIN'),permitir('GESTAO_GERENCIAR'),controller.listarPermissoes);
router.get('/configuracoes/tecnicos',perfil('GESTOR','ADMIN'),permitir('GESTAO_GERENCIAR'),controller.listarTecnicos);
router.post('/configuracoes/tecnicos',perfil('GESTOR','ADMIN'),permitir('GESTAO_GERENCIAR'),controller.criarTecnico);
router.put('/configuracoes/usuarios/:id/permissoes',perfil('GESTOR','ADMIN'),permitir('GESTAO_GERENCIAR'),controller.salvarPermissoes);
router.get('/configuracoes/checklists/:tipo',perfil('GESTOR','ADMIN'),permitir('GESTAO_GERENCIAR'),controller.listarChecklist);
router.put('/configuracoes/checklists/:tipo',perfil('GESTOR','ADMIN'),permitir('GESTAO_GERENCIAR'),controller.salvarChecklist);
module.exports=router;
