import React,{useRef,useState}from'react';
import{View,TouchableOpacity,Text,Image,StyleSheet,Alert,ActivityIndicator,TextInput}from'react-native';
import{CameraView,useCameraPermissions}from'expo-camera';
import*as ImageManipulator from'expo-image-manipulator';
import*as Location from'expo-location';
import*as FileSystem from'expo-file-system/legacy';
import{Ionicons}from'@expo/vector-icons';
import{api}from'../../services/api';
import{colors,shadow}from'../../styles/theme';
import{enfileirar}from'../../database/sqlite';

export default function CameraOS({route,navigation}){
 const{os_id}=route.params,tipo='EVIDENCIA';const[permission,requestPermission]=useCameraPermissions();
 const[foto,setFoto]=useState(null),[comentario,setComentario]=useState(''),[localizacao,setLocalizacao]=useState(null),[loading,setLoading]=useState(false);const camera=useRef(null);
 if(!permission)return <View style={s.center}><ActivityIndicator/></View>;
 if(!permission.granted)return <View style={s.center}><Text style={s.permission}>A câmera é necessária para registrar o serviço.</Text><TouchableOpacity style={s.smallButton}onPress={requestPermission}><Text style={s.white}>Permitir câmera</Text></TouchableOpacity></View>;
 const capturar=async()=>{try{const original=await camera.current?.takePictureAsync({quality:.8});if(!original)return;setFoto(await ImageManipulator.manipulateAsync(original.uri,[{resize:{width:1200}}],{compress:.75,format:ImageManipulator.SaveFormat.JPEG}));const p=await Location.requestForegroundPermissionsAsync();if(p.status==='granted'){const pos=await Location.getCurrentPositionAsync({accuracy:Location.Accuracy.Balanced});setLocalizacao({latitude:pos.coords.latitude,longitude:pos.coords.longitude})}}catch(e){Alert.alert('Câmera',e.message)}};
 const enviar=async()=>{setLoading(true);const agora=Date.now();const metadados={comentario:comentario.trim(),...localizacao,capturada_em:new Date().toISOString(),client_uuid:`foto-${os_id}-${agora}`};try{await api.uploadFoto(os_id,tipo,{uri:foto.uri,name:`os_${os_id}_${agora}.jpg`,type:'image/jpeg'},metadados);Alert.alert('Foto registrada','Você pode adicionar outra foto mais tarde pela O.S.',[{text:'Voltar à O.S.',onPress:()=>navigation.goBack()}])}catch(e){if(!e.status){const uri=`${FileSystem.documentDirectory}os_${os_id}_foto_${agora}.jpg`;await FileSystem.copyAsync({from:foto.uri,to:uri});await enfileirar('FOTO_OS',{os_id,tipo,uri,nome:`os_${os_id}_${agora}.jpg`,mime:'image/jpeg',metadados});Alert.alert('Foto salva offline','Ela será enviada automaticamente pela central de sincronização.',[{text:'Voltar à O.S.',onPress:()=>navigation.goBack()}])}else Alert.alert('Falha no upload',e.message)}finally{setLoading(false)}};
 return <View style={s.container}><View style={s.guide}><View style={s.step}><Ionicons name="camera-outline"size={20}color={colors.primary}/></View><View style={{flex:1}}><Text style={s.label}>Foto do atendimento</Text><Text style={s.hint}>A data e a localização são registradas automaticamente.</Text></View></View>{foto?<><View style={s.previewWrap}><Image source={{uri:foto.uri}}style={s.preview}/><View style={s.check}><Ionicons name="checkmark"size={25}color="#fff"/></View></View><TextInput style={s.comment}placeholder="Comentário da foto (opcional)"value={comentario}onChangeText={setComentario}maxLength={500}/>{localizacao&&<Text style={s.geo}>✓ Localização vinculada à evidência</Text>}<View style={s.actions}><TouchableOpacity style={[s.button,s.secondary]}onPress={()=>setFoto(null)}><Ionicons name="refresh"size={19}color={colors.text}/><Text style={s.secondaryText}>Refazer</Text></TouchableOpacity><TouchableOpacity style={[s.button,s.green]}onPress={enviar}disabled={loading}>{loading?<ActivityIndicator color="#fff"/>:<><Text style={s.white}>Salvar foto</Text><Ionicons name="cloud-upload-outline"size={19}color="#fff"/></>}</TouchableOpacity></View></>:<View style={s.cameraWrap}><CameraView style={s.camera}facing="back"ref={camera}/><View pointerEvents="none"style={s.frame}><Ionicons name="scan-outline"size={230}color="rgba(255,255,255,.8)"/></View><View style={s.cameraFooter}><Text style={s.cameraTip}>Centralize a evidência no quadro</Text><TouchableOpacity accessibilityLabel="Tirar foto"style={s.captureOuter}onPress={capturar}><View style={s.capture}/></TouchableOpacity></View></View>}</View>
}
const s=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},center:{flex:1,justifyContent:'center',alignItems:'center',padding:30},permission:{textAlign:'center',marginBottom:18,color:colors.text},guide:{flexDirection:'row',alignItems:'center',gap:13,padding:16,backgroundColor:'#fff',borderBottomWidth:1,borderColor:colors.border},step:{backgroundColor:'#E4F4F8',borderRadius:12,padding:9},label:{color:colors.text,fontSize:17,fontWeight:'800'},hint:{color:colors.muted,fontSize:12,marginTop:2},cameraWrap:{flex:1,margin:12,borderRadius:22,overflow:'hidden',backgroundColor:'#000',...shadow},camera:{flex:1},frame:{position:'absolute',top:'14%',left:0,right:0,alignItems:'center'},cameraFooter:{position:'absolute',left:0,right:0,bottom:0,alignItems:'center',paddingBottom:27},cameraTip:{color:'#fff',backgroundColor:'rgba(0,0,0,.5)',borderRadius:15,paddingHorizontal:13,paddingVertical:7,marginBottom:18,fontSize:12},captureOuter:{width:76,height:76,borderRadius:38,borderWidth:3,borderColor:'#fff',alignItems:'center',justifyContent:'center'},capture:{width:60,height:60,borderRadius:30,backgroundColor:'#fff'},previewWrap:{flex:1,margin:12,borderRadius:22,overflow:'hidden',backgroundColor:colors.navy},preview:{flex:1,resizeMode:'contain'},check:{position:'absolute',right:15,top:15,width:42,height:42,borderRadius:15,alignItems:'center',justifyContent:'center',backgroundColor:colors.success},comment:{marginHorizontal:12,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,borderRadius:12,padding:13,color:colors.text},geo:{marginHorizontal:15,marginTop:6,fontSize:11,color:colors.success,fontWeight:'700'},actions:{flexDirection:'row',padding:12,paddingBottom:20,gap:10},button:{flex:1,minHeight:54,borderRadius:14,alignItems:'center',justifyContent:'center',flexDirection:'row',gap:8},secondary:{backgroundColor:'#fff',borderWidth:1,borderColor:colors.border},secondaryText:{color:colors.text,fontWeight:'800'},green:{backgroundColor:colors.success},smallButton:{backgroundColor:colors.primary,padding:14,borderRadius:10},white:{color:'#fff',fontWeight:'800'}});
