import React, { useCallback, useState } from 'react';
import { View, Text, ScrollView, TouchableOpacity, StyleSheet, ActivityIndicator, Alert, Linking, Vibration, Image, TextInput } from 'react-native';
import * as Location from 'expo-location';
import { useFocusEffect } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import { api } from '../../services/api';
import { colors, shadow } from '../../styles/theme';
import { enfileirar, lerCache, salvarCache } from '../../database/sqlite';

export default function DetalhesOS({ route, navigation }) {
  const { os_id } = route.params; const [os, setOs] = useState(null); const [loading, setLoading] = useState(true); const [editandoAgenda,setEditandoAgenda]=useState(false);const[dataAgenda,setDataAgenda]=useState('');const[horaAgenda,setHoraAgenda]=useState('');
  const carregar = useCallback(async () => { try { const dados=await api.chamadaAutenticada(`/os/${os_id}`);setOs(dados);await salvarCache(`os_${os_id}`,dados); } catch(e) { const cache=await lerCache(`os_${os_id}`);if(cache)setOs(cache.dados);else Alert.alert('O.S.',e.message); } finally { setLoading(false); } }, [os_id]);
  useFocusEffect(useCallback(() => { carregar(); }, [carregar]));
  const evento = async (tipo) => {
    try {
      let coordenadas = {};
      if (['CHECKIN','CHECKOUT'].includes(tipo)) {
        const permissao = await Location.requestForegroundPermissionsAsync();
        if (permissao.status !== 'granted') return Alert.alert('Localização necessária', 'Autorize o GPS para registrar a presença no atendimento.');
        const posicao = await Location.getCurrentPositionAsync({ accuracy: Location.Accuracy.Balanced });
        coordenadas = { latitude: posicao.coords.latitude, longitude: posicao.coords.longitude };
      }
      await api.chamadaAutenticada(`/os/${os.id}/eventos`, 'POST', { evento: tipo, ...coordenadas });
      Vibration.vibrate(120); await carregar();
      if (tipo === 'CHECKIN') navigation.navigate('CameraOS', { os_id: os.id });
    }
    catch (e) { if (!e.status) { await enfileirar('EVENTO_OS',{os_id:os.id,dados:{evento:tipo,...coordenadas}}); if(tipo==='CHECKIN') navigation.navigate('CameraOS',{os_id:os.id}); else Alert.alert('Salvo offline','O evento será sincronizado quando a internet voltar.'); } else Alert.alert('Atendimento',e.message); }
  };
  const evidencias = (os?.fotos || []).filter((foto) => ['ANTES','DEPOIS','EVIDENCIA'].includes(foto.tipo));
  const removerFoto=(foto)=>Alert.alert('Excluir evidência','Deseja remover esta foto da O.S.?',[{text:'Cancelar',style:'cancel'},{text:'Excluir',style:'destructive',onPress:async()=>{try{await api.chamadaAutenticada(`/os/fotos/${foto.id}`,'DELETE');await carregar()}catch(e){Alert.alert('Foto',e.message)}}}]);
  const agendar=async()=>{if(!/^\d{4}-\d{2}-\d{2}$/.test(dataAgenda)||!/^\d{2}:\d{2}$/.test(horaAgenda)||Number.isNaN(Date.parse(`${dataAgenda}T${horaAgenda}:00`)))return Alert.alert('Agendamento','Use AAAA-MM-DD para a data e HH:MM para o horário.');const dados={agendado_para:new Date(`${dataAgenda}T${horaAgenda}:00`).toISOString()};try{await api.chamadaAutenticada(`/os/${os.id}/agendar`,'PATCH',dados);setEditandoAgenda(false);await carregar();Alert.alert('Agendamento','Data e horário atualizados.')}catch(e){if(!e.status){await enfileirar('AGENDAR_OS',{os_id:os.id,dados});setEditandoAgenda(false);Alert.alert('Salvo offline','O agendamento será enviado quando a conexão voltar.')}else Alert.alert('Agendamento',e.message)}};
  const iniciar = () => os.status === 'ABERTA' ? evento('CHECKIN') : evidencias.length < 2 ? navigation.navigate('CameraOS', { os_id: os.id }) : navigation.navigate('ExecucaoOS', { os_id: os.id });
  if (loading || !os) return <View style={styles.center}><ActivityIndicator size="large" color={colors.primary} /></View>;
  const equipamento = [os.aparelho_marca, os.aparelho_modelo, os.aparelho_capacidade].filter(Boolean).join(' · ') || 'Não vinculado';
  return <ScrollView style={styles.container} contentContainerStyle={styles.content}>
    <View style={styles.hero}><Text style={styles.order}>ORDEM DE SERVIÇO #{String(os.id).padStart(4, '0')}</Text><Text style={styles.title}>{os.tipo_servico.replaceAll('_', ' ')}</Text><View style={styles.status}><View style={styles.dot} /><Text style={styles.statusText}>{os.status.replaceAll('_', ' ')}</Text></View></View>
    <View style={styles.card}><Text style={styles.heading}>Cliente e local</Text><Row icon="person-outline" title={os.cliente_nome} text={os.cliente_telefone || 'Sem telefone'} /><Row icon="location-outline" title={os.cliente_endereco || 'Endereço não informado'} />
      <View style={styles.quick}><TouchableOpacity style={styles.quickButton} onPress={() => os.cliente_telefone && Linking.openURL(`tel:${os.cliente_telefone}`)}><Ionicons name="call-outline" size={19} color={colors.primary} /><Text style={styles.quickText}>Ligar</Text></TouchableOpacity><TouchableOpacity style={styles.quickButton} onPress={() => os.cliente_telefone && Linking.openURL(`https://wa.me/${os.cliente_telefone.replace(/\D/g, '')}`)}><Ionicons name="logo-whatsapp" size={19} color={colors.success} /><Text style={styles.quickText}>WhatsApp</Text></TouchableOpacity><TouchableOpacity style={styles.quickButton} onPress={() => navigation.navigate('MapaAtendimento', { cliente: os.cliente_nome, endereco: [os.cliente_endereco, os.cliente_cidade, os.cliente_estado, os.cliente_cep].filter(Boolean).join(', '), latitude: os.latitude, longitude: os.longitude })}><Ionicons name="map-outline" size={19} color={colors.primary} /><Text style={styles.quickText}>Ver mapa</Text></TouchableOpacity></View>
    </View>
    <View style={styles.card}><Text style={styles.heading}>Equipamento</Text><Row icon="snow-outline" title={equipamento} text={`Patrimônio vinculado à O.S. #${os.id}`} /></View>
    <View style={styles.card}><Text style={styles.heading}>Solicitação do cliente</Text><Text style={styles.description}>{os.descricao_problema}</Text></View>
    <View style={styles.card}><Text style={styles.heading}>Data e horário da visita</Text><Row icon="calendar-outline" title={os.agendado_para?new Date(os.agendado_para).toLocaleString('pt-BR'):'Visita ainda não agendada'} />{editandoAgenda?<><View style={styles.scheduleRow}><TextInput style={[styles.scheduleInput,{flex:1.35}]} value={dataAgenda} onChangeText={setDataAgenda} placeholder="AAAA-MM-DD"/><TextInput style={styles.scheduleInput} value={horaAgenda} onChangeText={setHoraAgenda} placeholder="HH:MM"/></View><View style={styles.scheduleActions}><TouchableOpacity onPress={()=>setEditandoAgenda(false)}><Text style={styles.cancelText}>Cancelar</Text></TouchableOpacity><TouchableOpacity style={styles.saveSchedule} onPress={agendar}><Text style={styles.saveScheduleText}>Salvar agendamento</Text></TouchableOpacity></View></>:!['FINALIZADA','CANCELADA'].includes(os.status)&&<TouchableOpacity style={styles.outlineAction} onPress={()=>{if(os.agendado_para){const d=new Date(os.agendado_para);setDataAgenda(`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`);setHoraAgenda(`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`)}setEditandoAgenda(true)}}><Ionicons name="calendar" size={19} color={colors.primary}/><Text style={styles.outlineText}>{os.agendado_para?'Alterar agendamento':'Agendar visita'}</Text></TouchableOpacity>}</View>
    <View style={styles.card}><Text style={styles.heading}>Andamento da visita</Text><View style={styles.eventRow}><Event done={os.a_caminho_em} icon="car-outline" label="A caminho" /><Event done={os.checkin_em} icon="location-outline" label="Check-in" /><Event done={os.checkout_em} icon="checkmark-done-outline" label="Check-out" /></View>{os.status === 'ABERTA' && !os.a_caminho_em && <TouchableOpacity style={styles.outlineAction} onPress={() => evento('A_CAMINHO')}><Ionicons name="car-outline" size={19} color={colors.primary} /><Text style={styles.outlineText}>Informar que estou a caminho</Text></TouchableOpacity>}{os.status === 'EM_ANDAMENTO' && !os.checkout_em && <TouchableOpacity style={styles.outlineAction} onPress={() => evento('CHECKOUT')}><Ionicons name="exit-outline" size={19} color={colors.primary} /><Text style={styles.outlineText}>Registrar saída com GPS</Text></TouchableOpacity>}</View>
    <View style={styles.card}><Text style={styles.heading}>Galeria do atendimento</Text><Text style={styles.description}>{evidencias.length} de 2 fotos mínimas registradas.</Text><ScrollView horizontal showsHorizontalScrollIndicator={false} style={{marginTop:12}}>{evidencias.map(f=><TouchableOpacity key={f.id||f.url} style={styles.photoCard} onLongPress={()=>removerFoto(f)}><Image source={{uri:f.url}} style={styles.photo}/><Text numberOfLines={2} style={styles.photoComment}>{f.comentario||'Sem comentário'}</Text><Text style={styles.photoDate}>{new Date(f.capturada_em||f.created_at).toLocaleString('pt-BR')}</Text>{f.latitude&&<Ionicons name="location" size={13} color={colors.success}/>}</TouchableOpacity>)}</ScrollView>{os.status === 'EM_ANDAMENTO' && <TouchableOpacity style={styles.outlineAction} onPress={() => navigation.navigate('CameraOS',{os_id:os.id})}><Ionicons name="camera-outline" size={19} color={colors.primary}/><Text style={styles.outlineText}>Adicionar foto</Text></TouchableOpacity>}<Text style={styles.photoHelp}>Segure uma foto para excluí-la antes da finalização.</Text></View>
    {os.status==='EM_ANDAMENTO'&&<View style={styles.card}><Text style={styles.heading}>Controle de tempo</Text><Text style={styles.description}>{os.pausado_em?'Atendimento pausado. Retome quando voltar ao serviço.':'O cronômetro está registrando o tempo efetivo da visita.'}</Text><TouchableOpacity style={[styles.outlineAction,os.pausado_em&&{borderColor:colors.success}]} onPress={()=>evento(os.pausado_em?'RETOMAR':'PAUSAR')}><Ionicons name={os.pausado_em?'play':'pause'} size={19} color={os.pausado_em?colors.success:colors.primary}/><Text style={[styles.outlineText,os.pausado_em&&{color:colors.success}]}>{os.pausado_em?'Retomar atendimento':'Pausar atendimento'}</Text></TouchableOpacity></View>}
    <View style={styles.card}><Text style={styles.heading}>Histórico do equipamento</Text>{os.historico_equipamento.length ? os.historico_equipamento.map((h) => <View key={h.id} style={styles.history}><View><Text style={styles.historyTitle}>O.S. #{h.id} · {h.tipo_servico.replaceAll('_', ' ')}</Text><Text style={styles.historyText}>{h.diagnostico || 'Sem diagnóstico registrado'}</Text></View><Ionicons name="checkmark-circle" size={20} color={colors.success} /></View>) : <Text style={styles.empty}>Este é o primeiro atendimento registrado neste equipamento.</Text>}</View>
    <TouchableOpacity style={styles.start} onPress={iniciar}><Ionicons name={os.status==='ABERTA'?'play-circle-outline':evidencias.length<2?'camera-outline':'document-text-outline'} size={23} color="#fff" /><Text style={styles.startText}>{os.status==='ABERTA'?'Iniciar atendimento':evidencias.length<2?`Adicionar foto (${evidencias.length}/2)`:'Preencher relatório técnico'}</Text></TouchableOpacity>
  </ScrollView>;
}
function Row({ icon, title, text }) { return <View style={styles.row}><View style={styles.rowIcon}><Ionicons name={icon} size={20} color={colors.primary} /></View><View style={{ flex: 1 }}><Text style={styles.rowTitle}>{title}</Text>{text && <Text style={styles.rowText}>{text}</Text>}</View></View>; }
function Event({ done, icon, label }) { return <View style={styles.event}><View style={[styles.eventIcon, done && styles.eventDone]}><Ionicons name={done ? 'checkmark' : icon} size={17} color={done ? '#fff' : colors.muted} /></View><Text style={[styles.eventLabel, done && { color: colors.success }]}>{label}</Text></View>; }
const styles = StyleSheet.create({
  photoCard:{width:145,marginRight:10,backgroundColor:colors.background,borderRadius:12,padding:7},photo:{width:131,height:95,borderRadius:9,backgroundColor:colors.border},photoComment:{fontSize:11,fontWeight:'700',color:colors.text,marginTop:6},photoDate:{fontSize:9,color:colors.muted,marginVertical:3},photoHelp:{fontSize:10,color:colors.muted,textAlign:'center',marginTop:8},
  scheduleRow:{flexDirection:'row',gap:8,marginTop:12},scheduleInput:{flex:1,backgroundColor:colors.background,borderWidth:1,borderColor:colors.border,borderRadius:11,padding:12,color:colors.text},scheduleActions:{marginTop:10,flexDirection:'row',alignItems:'center',justifyContent:'flex-end',gap:16},cancelText:{color:colors.muted,fontWeight:'700'},saveSchedule:{backgroundColor:colors.primary,borderRadius:10,paddingHorizontal:14,paddingVertical:11},saveScheduleText:{color:'#fff',fontWeight:'800'},
  container: { flex: 1, backgroundColor: colors.background }, content: { padding: 16, paddingBottom: 35 }, center: { flex: 1, justifyContent: 'center', alignItems: 'center' }, hero: { backgroundColor: colors.navy, borderRadius: 20, padding: 20, marginBottom: 13, ...shadow }, order: { color: '#9CC9D7', fontSize: 11, fontWeight: '800', letterSpacing: .8 }, title: { color: '#fff', fontSize: 24, fontWeight: '900', marginVertical: 9 }, status: { flexDirection: 'row', alignItems: 'center', gap: 7 }, dot: { width: 7, height: 7, borderRadius: 4, backgroundColor: colors.warning }, statusText: { color: '#DDECF1', fontSize: 12, fontWeight: '700' },
  card: { backgroundColor: '#fff', borderRadius: 18, padding: 17, marginBottom: 13, borderWidth: 1, borderColor: colors.border, ...shadow }, heading: { color: colors.text, fontWeight: '900', fontSize: 16, marginBottom: 13 }, row: { flexDirection: 'row', gap: 11, alignItems: 'center', marginVertical: 6 }, rowIcon: { width: 38, height: 38, borderRadius: 12, backgroundColor: '#E8F4F7', alignItems: 'center', justifyContent: 'center' }, rowTitle: { color: colors.text, fontWeight: '700' }, rowText: { color: colors.muted, fontSize: 12, marginTop: 2 }, quick: { flexDirection: 'row', gap: 8, marginTop: 14 }, quickButton: { flex: 1, backgroundColor: colors.background, borderRadius: 11, paddingVertical: 10, alignItems: 'center', gap: 4 }, quickText: { color: colors.text, fontSize: 11, fontWeight: '700' }, description: { color: colors.muted, lineHeight: 21 }, eventRow:{flexDirection:'row',justifyContent:'space-between'},event:{alignItems:'center',flex:1},eventIcon:{width:36,height:36,borderRadius:18,backgroundColor:colors.background,alignItems:'center',justifyContent:'center'},eventDone:{backgroundColor:colors.success},eventLabel:{fontSize:11,color:colors.muted,fontWeight:'700',marginTop:5},outlineAction:{marginTop:15,borderWidth:1,borderColor:colors.primary,borderRadius:12,padding:12,flexDirection:'row',justifyContent:'center',alignItems:'center',gap:7},outlineText:{color:colors.primary,fontWeight:'800'}, history: { flexDirection: 'row', justifyContent: 'space-between', paddingVertical: 11, borderTopWidth: 1, borderTopColor: '#EDF2F4' }, historyTitle: { color: colors.text, fontWeight: '700', fontSize: 12 }, historyText: { color: colors.muted, fontSize: 11, marginTop: 3, maxWidth: 270 }, empty: { color: colors.muted, fontStyle: 'italic' }, start: { minHeight: 58, borderRadius: 16, backgroundColor: colors.success, flexDirection: 'row', alignItems: 'center', justifyContent: 'center', gap: 9, ...shadow }, startText: { color: '#fff', fontWeight: '900', fontSize: 16 },
});
