const { z } = require('zod');
const db = require('../config/database');

const servicoSchema = z.object({
  nome: z.string().trim().min(2).max(150), descricao: z.string().trim().max(1000).optional().default(''),
  categoria: z.string().trim().max(100).optional().default(''), custo: z.coerce.number().nonnegative(),
  preco: z.coerce.number().nonnegative(), garantia_dias: z.coerce.number().int().min(0).max(3650),
  duracao_minutos: z.coerce.number().int().min(0).max(10080).nullable().optional(),
}).strict();
const produtoSchema = z.object({
  nome: z.string().trim().min(2).max(150), sku: z.string().trim().max(80).optional().default(''),
  categoria: z.string().trim().max(100).optional().default(''), unidade: z.string().trim().min(1).max(20),
  custo: z.coerce.number().nonnegative(), preco: z.coerce.number().nonnegative(),
  estoque_minimo: z.coerce.number().nonnegative(),
}).strict();

class CatalogoController {
  async atualizarServico(req,res){const v=servicoSchema.safeParse(req.body);if(!v.success)return res.status(400).json({erro:'Serviço inválido.',detalhes:v.error.issues});try{const d=v.data,r=await db.query(`UPDATE catalogo_servicos SET nome=$1,descricao=$2,categoria=$3,custo=$4,preco=$5,garantia_dias=$6,duracao_minutos=$7,updated_at=NOW() WHERE id=$8 AND empresa_id=$9 AND ativo=TRUE RETURNING *`,[d.nome,d.descricao||null,d.categoria||null,d.custo,d.preco,d.garantia_dias,d.duracao_minutos||null,req.params.id,req.usuarioLogado.empresa_id]);if(!r.rows[0])return res.status(404).json({erro:'Serviço não encontrado.'});return res.json(r.rows[0])}catch(e){return res.status(500).json({erro:'Falha ao atualizar serviço.'})}}
  async inativarServico(req,res){try{const r=await db.query('UPDATE catalogo_servicos SET ativo=FALSE,updated_at=NOW() WHERE id=$1 AND empresa_id=$2 AND ativo=TRUE RETURNING id',[req.params.id,req.usuarioLogado.empresa_id]);if(!r.rows[0])return res.status(404).json({erro:'Serviço não encontrado.'});return res.sendStatus(204)}catch(e){return res.status(500).json({erro:'Falha ao inativar serviço.'})}}
  async atualizarProduto(req,res){const v=produtoSchema.safeParse(req.body);if(!v.success)return res.status(400).json({erro:'Produto inválido.',detalhes:v.error.issues});try{const d=v.data,r=await db.query(`UPDATE produtos SET nome=$1,sku=$2,categoria=$3,unidade=$4,custo=$5,preco=$6,estoque_minimo=$7,updated_at=NOW() WHERE id=$8 AND empresa_id=$9 AND ativo=TRUE RETURNING *`,[d.nome,d.sku||null,d.categoria||null,d.unidade,d.custo,d.preco,d.estoque_minimo,req.params.id,req.usuarioLogado.empresa_id]);if(!r.rows[0])return res.status(404).json({erro:'Produto não encontrado.'});return res.json(r.rows[0])}catch(e){if(e.code==='23505')return res.status(409).json({erro:'Já existe um produto com este SKU.'});return res.status(500).json({erro:'Falha ao atualizar produto.'})}}
  async inativarProduto(req,res){try{const r=await db.query('UPDATE produtos SET ativo=FALSE,updated_at=NOW() WHERE id=$1 AND empresa_id=$2 AND ativo=TRUE RETURNING id',[req.params.id,req.usuarioLogado.empresa_id]);if(!r.rows[0])return res.status(404).json({erro:'Produto não encontrado.'});return res.sendStatus(204)}catch(e){return res.status(500).json({erro:'Falha ao inativar produto.'})}}
  async movimentacoes(req,res){try{const produto=await db.query('SELECT id,nome,estoque,unidade FROM produtos WHERE id=$1 AND empresa_id=$2',[req.params.id,req.usuarioLogado.empresa_id]);if(!produto.rows[0])return res.status(404).json({erro:'Produto não encontrado.'});const mov=await db.query(`SELECT m.*,u.nome usuario_nome,t.nome tecnico_nome FROM estoque_movimentos m LEFT JOIN usuarios u ON u.id=m.usuario_id LEFT JOIN usuarios t ON t.id=m.tecnico_id WHERE m.produto_id=$1 AND m.empresa_id=$2 ORDER BY m.created_at DESC LIMIT 200`,[req.params.id,req.usuarioLogado.empresa_id]);return res.json({...produto.rows[0],movimentacoes:mov.rows})}catch(e){return res.status(500).json({erro:'Falha ao carregar movimentações.'})}}
  async devolverTecnico(req,res){const tecnico=Number(req.body.tecnico_id),quantidade=Number(req.body.quantidade),produto=Number(req.params.id);if(!Number.isInteger(tecnico)||!Number.isFinite(quantidade)||quantidade<=0)return res.status(400).json({erro:'Devolução inválida.'});try{await db.transaction(async c=>{const saldo=await c.query(`SELECT et.quantidade,p.nome FROM estoque_tecnico et JOIN produtos p ON p.id=et.produto_id WHERE et.tecnico_id=$1 AND et.produto_id=$2 AND p.empresa_id=$3 FOR UPDATE OF et`,[tecnico,produto,req.usuarioLogado.empresa_id]);if(!saldo.rows[0])throw Object.assign(new Error('Saldo do técnico não encontrado.'),{status:404});if(Number(saldo.rows[0].quantidade)<quantidade)throw Object.assign(new Error('Quantidade maior que o saldo do técnico.'),{status:422});await c.query('UPDATE estoque_tecnico SET quantidade=quantidade-$1,updated_at=NOW() WHERE tecnico_id=$2 AND produto_id=$3',[quantidade,tecnico,produto]);await c.query('UPDATE produtos SET estoque=estoque+$1,updated_at=NOW() WHERE id=$2 AND empresa_id=$3',[quantidade,produto,req.usuarioLogado.empresa_id]);await c.query("INSERT INTO estoque_movimentos(empresa_id,produto_id,tipo,quantidade,observacao,usuario_id,tecnico_id)VALUES($1,$2,'ENTRADA',$3,'Devolução do estoque do técnico',$4,$5)",[req.usuarioLogado.empresa_id,produto,quantidade,req.usuarioLogado.usuario_id,tecnico])});return res.sendStatus(204)}catch(e){return res.status(e.status||500).json({erro:e.message||'Falha na devolução.'})}}
}
module.exports=new CatalogoController();
