import React,{useCallback,useState} from 'react';
import {View,Text,FlatList,TouchableOpacity,StyleSheet,ActivityIndicator,Alert} from 'react-native';
import {useFocusEffect} from '@react-navigation/native';
import {Ionicons} from '@expo/vector-icons';
import {api} from '../../services/api'; import {colors,shadow} from '../../styles/theme';
export default function Clientes({navigation}){
 const [dados,setDados]=useState([]),[loading,setLoading]=useState(true);
 const load=useCallback(()=>api.chamadaAutenticada('/clientes').then(setDados).catch(e=>Alert.alert('Clientes',e.message)).finally(()=>setLoading(false)),[]);
 useFocusEffect(useCallback(()=>{load()},[load]));
 if(loading)return <View style={s.center}><ActivityIndicator size="large" color={colors.primary}/></View>;
 return <View style={s.container}><View style={s.actions}><TouchableOpacity style={s.scan} onPress={()=>navigation.navigate('LeitorQR')}><Ionicons name="qr-code-outline" size={21} color={colors.primary}/><Text style={s.scanText}>Ler QR Code</Text></TouchableOpacity><TouchableOpacity style={s.add} onPress={()=>navigation.navigate('ClienteForm')}><Ionicons name="person-add-outline" size={20} color="#fff"/><Text style={s.addText}>Novo cliente</Text></TouchableOpacity></View>
 <FlatList data={dados} keyExtractor={x=>String(x.id)} contentContainerStyle={s.list} ListEmptyComponent={<Text style={s.empty}>Nenhum cliente cadastrado.</Text>} renderItem={({item})=><View style={s.card}><View style={s.clientTop}><View style={s.avatar}><Text style={s.avatarText}>{item.nome.slice(0,2).toUpperCase()}</Text></View><View style={{flex:1}}><Text style={s.name}>{item.nome}</Text><Text style={s.muted}>{item.telefone||'Sem telefone'}</Text></View><TouchableOpacity onPress={()=>navigation.navigate('ClienteForm',{cliente:item})}><Ionicons name="create-outline" size={21} color={colors.muted}/></TouchableOpacity></View><View style={s.address}><Ionicons name="location-outline" size={16} color={colors.muted}/><Text style={s.muted}>{item.endereco||'Endereço não informado'}</Text></View><Text style={s.section}>{item.aparelhos.length} EQUIPAMENTO(S)</Text>{item.aparelhos.map(eq=><TouchableOpacity key={eq.id} style={s.equipment} onPress={()=>navigation.navigate('EquipamentoDetalhe',{equipamento_id:eq.id})}><Ionicons name="snow-outline" size={21} color={colors.primary}/><View style={{flex:1}}><Text style={s.eqName}>{eq.marca||'Equipamento'} {eq.modelo}</Text><Text style={s.muted}>{eq.ambiente||eq.capacidade||'Sem detalhes'}</Text></View><Ionicons name="chevron-forward" size={19} color={colors.muted}/></TouchableOpacity>)}<TouchableOpacity style={s.addEq} onPress={()=>navigation.navigate('EquipamentoForm',{cliente_id:item.id,cliente_nome:item.nome})}><Ionicons name="add" size={18} color={colors.primary}/><Text style={s.addEqText}>Adicionar equipamento</Text></TouchableOpacity></View>}/></View>
}
const s=StyleSheet.create({container:{flex:1,backgroundColor:colors.background},center:{flex:1,justifyContent:'center'},actions:{flexDirection:'row',gap:9,padding:16,paddingBottom:5},scan:{flex:1,minHeight:48,borderRadius:13,backgroundColor:'#fff',borderWidth:1,borderColor:colors.border,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},scanText:{color:colors.primary,fontWeight:'800'},add:{flex:1,minHeight:48,borderRadius:13,backgroundColor:colors.primary,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:7},addText:{color:'#fff',fontWeight:'800'},list:{padding:16,paddingTop:10},card:{backgroundColor:'#fff',borderRadius:18,padding:16,marginBottom:13,borderWidth:1,borderColor:colors.border,...shadow},clientTop:{flexDirection:'row',alignItems:'center',gap:11},avatar:{width:45,height:45,borderRadius:15,backgroundColor:'#E4F4F8',alignItems:'center',justifyContent:'center'},avatarText:{color:colors.primary,fontWeight:'900'},name:{color:colors.text,fontSize:17,fontWeight:'900'},muted:{color:colors.muted,fontSize:12},address:{flexDirection:'row',gap:6,marginTop:11},section:{color:colors.muted,fontSize:10,fontWeight:'900',letterSpacing:.8,marginTop:17,marginBottom:7},equipment:{flexDirection:'row',gap:10,alignItems:'center',paddingVertical:11,borderTopWidth:1,borderTopColor:'#EDF2F4'},eqName:{color:colors.text,fontWeight:'700'},addEq:{flexDirection:'row',gap:5,alignItems:'center',paddingTop:12},addEqText:{color:colors.primary,fontWeight:'800',fontSize:12},empty:{textAlign:'center',color:colors.muted,marginTop:60}});
