import React, { useCallback, useState } from 'react';
import { ActivityIndicator, Alert, FlatList, StyleSheet, Text, TouchableOpacity, View } from 'react-native';
import { useFocusEffect } from '@react-navigation/native';
import { Ionicons } from '@expo/vector-icons';
import { listarFila } from '../../database/sqlite';
import { tentarSincronizarOffline } from '../../services/SyncService';
import { colors, shadow } from '../../styles/theme';

const nomes={CRIAR_OS:'Nova O.S.',EVENTO_OS:'Evento da visita',FOTO_OS:'Foto/assinatura',EXECUCAO_OS:'Relatório técnico',RETORNO_OS:'Visita de retorno',STATUS_OS:'Mudança de status'};
export default function Sincronizacao(){const[itens,setItens]=useState([]),[loading,setLoading]=useState(false),[reenviando,setReenviando]=useState(null);const carregar=useCallback(()=>listarFila().then(setItens),[]);useFocusEffect(useCallback(()=>{carregar()},[carregar]));const sincronizar=async(id=null)=>{id===null?setLoading(true):setReenviando(id);try{const r=await tentarSincronizarOffline(id);await carregar();Alert.alert('Sincronização',r.enviados?'Item enviado com sucesso.':'O item continua pendente. Verifique a mensagem de erro.')}catch(e){Alert.alert('Sincronização',e.message)}finally{setLoading(false);setReenviando(null)}};return <View style={styles.page}><View style={styles.hero}><Ionicons name={itens.length?'cloud-upload-outline':'cloud-done-outline'} size={36} color="#fff"/><Text style={styles.number}>{itens.length}</Text><Text style={styles.label}>item(ns) aguardando envio</Text></View><TouchableOpacity style={styles.button} onPress={()=>sincronizar()} disabled={loading}>{loading?<ActivityIndicator color="#fff"/>:<><Ionicons name="sync" size={20} color="#fff"/><Text style={styles.buttonText}>Sincronizar tudo</Text></>}</TouchableOpacity><FlatList data={itens} keyExtractor={(i)=>String(i.id)} contentContainerStyle={styles.list} ListEmptyComponent={<Text style={styles.empty}>Todos os dados estão sincronizados.</Text>} renderItem={({item})=><View style={styles.card}><View style={styles.icon}><Ionicons name="time-outline" size={20} color={colors.warning}/></View><View style={{flex:1}}><Text style={styles.title}>{nomes[item.tipo]||item.tipo}</Text><Text style={styles.meta}>Criado em {new Date(`${item.created_at}Z`).toLocaleString('pt-BR')} · {item.tentativas} tentativa(s)</Text>{item.ultimo_erro&&<Text style={styles.error}>{item.ultimo_erro}</Text>}</View><TouchableOpacity style={styles.retry} onPress={()=>sincronizar(item.id)} disabled={reenviando===item.id}>{reenviando===item.id?<ActivityIndicator size="small" color={colors.primary}/>:<Ionicons name="refresh" size={20} color={colors.primary}/>}</TouchableOpacity></View>}/></View>}
const styles=StyleSheet.create({page:{flex:1,backgroundColor:colors.background,padding:16},hero:{backgroundColor:colors.navy,borderRadius:20,padding:20,alignItems:'center',...shadow},number:{fontSize:30,fontWeight:'900',color:'#fff',marginTop:4},label:{color:'#CDEAF2'},button:{minHeight:54,borderRadius:14,backgroundColor:colors.primary,marginTop:12,flexDirection:'row',alignItems:'center',justifyContent:'center',gap:8},buttonText:{color:'#fff',fontWeight:'900'},list:{paddingVertical:14},card:{backgroundColor:'#fff',borderRadius:15,padding:14,marginBottom:9,flexDirection:'row',alignItems:'center',gap:11,borderWidth:1,borderColor:colors.border},icon:{width:38,height:38,borderRadius:12,backgroundColor:'#FFF2D8',alignItems:'center',justifyContent:'center'},retry:{width:38,height:38,borderRadius:12,backgroundColor:'#EAF6F9',alignItems:'center',justifyContent:'center'},title:{color:colors.text,fontWeight:'800'},meta:{color:colors.muted,fontSize:11,marginTop:3},error:{color:colors.danger,fontSize:11,marginTop:4},empty:{textAlign:'center',color:colors.muted,marginTop:40}});
