import React,{useCallback,useEffect,useMemo,useState}from'react';import{api}from'../services/api';
export default function Operacao(){
 const[catalogo,setCatalogo]=useState({servicos:[],produtos:[]}),[contratos,setContratos]=useState([]),[orcamentos,setOrcamentos]=useState([]),[estoqueTecnicos,setEstoqueTecnicos]=useState([]),[tecnico,setTecnico]=useState(''),[quantidades,setQuantidades]=useState({}),[msg,setMsg]=useState('');
 const load=useCallback(()=>Promise.allSettled([api.get('/catalogo'),api.get('/contratos'),api.get('/orcamentos'),api.get('/estoque/tecnicos')]).then(([a,b,c,d])=>{if(a.value)setCatalogo(a.value.data);if(b.value)setContratos(b.value.data);if(c.value)setOrcamentos(c.value.data);if(d.value)setEstoqueTecnicos(d.value.data)}),[]);useEffect(()=>{load()},[load]);
 const tecnicos=useMemo(()=>Object.values(estoqueTecnicos.reduce((a,x)=>(a[x.tecnico_id]??={id:x.tecnico_id,nome:x.tecnico_nome},a),{})),[estoqueTecnicos]);
 const agrupado=Object.values(estoqueTecnicos.reduce((a,x)=>{(a[x.tecnico_id]??={nome:x.tecnico_nome,itens:[]}).itens.push(x);return a},{}));
 const transferir=async p=>{const quantidade=Number(quantidades[p.id]);if(!tecnico||!quantidade)return setMsg('Selecione o técnico e informe a quantidade.');try{await api.post(`/produtos/${p.id}/transferir-tecnico`,{tecnico_id:Number(tecnico),quantidade});setMsg(`${quantidade} ${p.unidade} de ${p.nome} transferido.`);setQuantidades({...quantidades,[p.id]:''});await load()}catch(e){setMsg(e.response?.data?.erro||e.message)}};
 return <div className="grid2"><section className="panel"><h2>Estoque central e transferências</h2><select value={tecnico}onChange={e=>setTecnico(e.target.value)}><option value="">Selecione o técnico/veículo</option>{tecnicos.map(t=><option key={t.id}value={t.id}>{t.nome}</option>)}</select>{catalogo.produtos.map(p=><div className="line"key={p.id}><span>{p.nome}<small>Central: {p.estoque} {p.unidade}</small></span><span style={{display:'flex',gap:6}}><input style={{width:75}}type="number"min="0.01"step="0.01"placeholder="Qtd."value={quantidades[p.id]||''}onChange={e=>setQuantidades({...quantidades,[p.id]:e.target.value})}/><button onClick={()=>transferir(p)}>Transferir</button></span></div>)}{msg&&<p>{msg}</p>}</section><section className="panel"><h2>Estoque nos veículos</h2>{agrupado.length?agrupado.map(t=><div key={t.nome}><h3>{t.nome}</h3>{t.itens.filter(i=>Number(i.quantidade)>0).map(i=><div className="line"key={i.produto_id}><span>{i.produto_nome}</span><b>{i.quantidade} {i.unidade}</b></div>)}</div>):<p className="empty">Nenhum material transferido.</p>}</section><section className="panel"><h2>Contratos preventivos</h2>{contratos.map(c=><div className="line"key={c.id}><span>{c.cliente_nome}<small>{c.nome}</small></span><b>{c.proxima_visita}</b></div>)}</section><section className="panel"><h2>Orçamentos</h2>{orcamentos.map(o=><div className="line"key={o.id}><span>#{o.id} · {o.cliente_nome}</span><b>{o.status}</b></div>)}</section><section className="panel"><h2>Serviços</h2>{catalogo.servicos.map(s=><div className="line"key={s.id}><span>{s.nome}</span><b>R$ {Number(s.preco).toFixed(2)}</b></div>)}</section></div>
}
